services:
  - type: web
    name: your-app-name
    env: python
    pythonVersion: "3.12.4"
    buildCommand: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
